volumes:
  demaf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./volume
  winery:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./winery
  rabbitmq_data:
  rabbitmq_logs:

services:
  # Message Broker
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: demaf-rabbitmq
    container_name: demaf-rabbitmq
    volumes:
      #  - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      #  - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Databases
  modelsdatabase:
    image: mongo:5.0.6
    hostname: modelsdatabase
    container_name: modelsdatabase
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tad
      MONGO_INITDB_ROOT_PASSWORD: tad
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  configurationsdatabase:
    image: postgres:14.2
    hostname: configurationsdatabase
    container_name: configurationsdatabase
    restart: always
    environment:
      POSTGRES_USER: tad
      POSTGRES_PASSWORD: tad
      POSTGRES_DB: configurations
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "tad"]
      interval: 10s
      timeout: 5s
      retries: 3

  tasksdatabase:
    image: postgres:14.2
    hostname: tasksdatabase
    container_name: tasksdatabase
    restart: always
    environment:
      POSTGRES_USER: tad
      POSTGRES_PASSWORD: tad
      POSTGRES_DB: tasks
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "tad"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Core Services
  analysismanager:
    image: well5a/analysis-manager:testing
    hostname: analysismanager
    container_name: analysismanager
    depends_on:
      rabbitmq:
        condition: service_healthy
      configurationsdatabase:
        condition: service_healthy
      tasksdatabase:
        condition: service_healthy
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.configurations-datasource.jdbcUrl": "jdbc:postgresql://configurationsdatabase:5432/configurations",
        "spring.configurations-datasource.username": "tad",
        "spring.configurations-datasource.password": "tad",
        "spring.tasks-datasource.jdbcUrl": "jdbc:postgresql://tasksdatabase:5432/tasks",
        "spring.tasks-datasource.username": "tad",
        "spring.tasks-datasource.password": "tad",
        "models-service.url": "http://modelsservice:8081/",
        "spring.rabbitmq.host": "rabbitmq"
        }'
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/actuator/health | grep 'UP' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  modelsservice:
    image: well5a/models-service:latest
    hostname: modelsservice
    container_name: modelsservice
    depends_on:
      modelsdatabase:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always
    environment:
      SPRING_DATA_MONGODB_USERNAME: tad
      SPRING_DATA_MONGODB_PASSWORD: tad
      SPRING_DATA_MONGODB_DATABASE: modelsdatabase
      SPRING_DATA_MONGODB_HOST: modelsdatabase
      SPRING_DATA_MONGODB_PORT: 27017
      TADM_OUTPUT_DIRECTORY: /usr/share/tadms
    volumes:
      - demaf:/usr/share
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8081/actuator/health | grep 'UP' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Plugins
  bashplugin:
    image: well5a/bash-plugin:testing
    hostname: bashplugin
    container_name: bashplugin
    depends_on:
      analysismanager:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always
    environment:
      ANALYSIS_MANAGER_PLUGIN_REGISTRATION_URL: http://analysismanager:8080/plugin-registration
      MODELS_SERVICE_URL: http://modelsservice:8081
      SPRING_RABBITMQ_HOST: rabbitmq
    volumes:
      - demaf:/usr/share
    ports:
      - 8083:8083
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8083/actuator/health | grep 'UP' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  terraformplugin:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: terraformplugin
    container_name: terraformplugin
    depends_on:
      analysismanager:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always
    environment:
      ANALYSIS_MANAGER_PLUGIN_REGISTRATION_URL: http://analysismanager:8080/plugin-registration
      MODELS_SERVICE_URL: http://modelsservice:8081
      SPRING_RABBITMQ_HOST: rabbitmq
      RUNPROVIDERPOSTPROCESSORS: true # default true
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    volumes:
      - demaf:/usr/share
    ports:
      - 8084:8084
      - 5005:5005
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8084/actuator/health | grep 'UP' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  kubernetesplugin:
    image: well5a/kubernetes-mps-plugin:testing
    hostname: kubernetesplugin
    container_name: kubernetesplugin
    depends_on:
      analysismanager:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always
    environment:
      ANALYSIS_MANAGER_PLUGIN_REGISTRATION_URL: http://analysismanager:8080/plugin-registration
      MODELS_SERVICE_URL: http://modelsservice:8081
      SPRING_RABBITMQ_HOST: rabbitmq
    volumes:
      - demaf:/usr/share
    ports:
      - 8085:8085
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8085/actuator/health | grep 'UP' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  helmplugin:
    image: well5a/helm-plugin:testing
    hostname: helmplugin
    container_name: helmplugin
    depends_on:
      analysismanager:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always
    environment:
      ANALYSIS_MANAGER_PLUGIN_REGISTRATION_URL: http://analysismanager:8080/plugin-registration
      MODELS_SERVICE_URL: http://modelsservice:8081
      SPRING_RABBITMQ_HOST: rabbitmq
      KUBE_OUTPUT_DIRECTORY: /usr/share/helmTemplates
    volumes:
      - demaf:/usr/share
      - ./helmPlugin/helm:/usr/local/bin/helm
    ports:
      - 8086:8086
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8086/actuator/health | grep 'UP' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

