name: buildAndPushImage

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
env:
  IMAGE_NAME: terraform-mps-plugin
  IMAGE_TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || 'testing' }}
jobs:
  build-with-paketo-push-2-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          
      - name: Login to DockerHub Container Registry
        run: echo $DOCKER_HUB_TOKEN | docker login -u well5a --password-stdin
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKERHUBTOKEN }}

      - name: Install pack CLI via the official buildpack Action https://github.com/buildpacks/github-actions#setup-pack-cli-action
        uses: buildpacks/github-actions/setup-pack@v4.8.0

      - name: Build app with pack CLI using Buildpack Cache image (see https://buildpacks.io/docs/app-developer-guide/using-cache-image/) & publish to Docker Hub
        run: |
          pack build index.docker.io/well5a/$IMAGE_NAME:$IMAGE_TAG \
              --builder paketobuildpacks/builder:base \
              --path . \
              --env BP_INCLUDE_FILES="mps-transformation-terraform/*" \
              --env BP_JVM_VERSION=11 \
              --env BPL_JAVA_NMT_ENABLED=false \
              --cache-image index.docker.io/well5a/$IMAGE_NAME-paketo-cache-image:$IMAGE_TAG \
              --publish
