# Runs Build without Docker
name: workflow-build

on:
  push:
    branches:
      - '*'

env:
  IMAGE_NAME: terraform-mps-plugin

jobs:
  build:
    runs-on: ubuntu-latest
    services:
        rabbitmq:
          image: rabbitmq:3.9-management
          options: -h rabbitmq --name rabbitmq
          ports:
            - 5672:5672
            - 15672:15672
          volumes:
            - rabbitmq_data:/var/lib/rabbitmq
            - rabbitmq_logs:/var/log/rabbitmq

        modelsdatabase:
          image: mongo:5.0.6
          options: -h modelsdatabase --name modelsdatabase
          env:
            MONGO_INITDB_ROOT_USERNAME: tad
            MONGO_INITDB_ROOT_PASSWORD: tad
          ports:
            - 27017:27017

        configurationsdatabase:
          image: postgres:14.2
          options: -h configurationsdatabase --name configurationsdatabase
          env:
            POSTGRES_USER: tad
            POSTGRES_PASSWORD: tad
            POSTGRES_DB: configurations
          ports:
            - 5432:5432

        tasksdatabase:
          image: postgres:14.2
          options: -h tasksdatabase --name tasksdatabase
          env:
            POSTGRES_USER: tad
            POSTGRES_PASSWORD: tad
            POSTGRES_DB: tasks
          ports:
            - 5433:5432

        analysismanager:
          image: well5a/analysis-manager:testing
          options: -h analysismanager --name analysismanager
          env:
            SPRING_APPLICATION_JSON: '{
              "spring.configurations-datasource.jdbcUrl": "jdbc:postgresql://localhost:5432/configurations",
              "spring.configurations-datasource.username": "tad",
              "spring.configurations-datasource.password": "tad",
              "spring.tasks-datasource.jdbcUrl": "jdbc:postgresql://localhost:5432/tasks",
              "spring.tasks-datasource.username": "tad",
              "spring.tasks-datasource.password": "tad",
              "models-service.url": "http://localhost:8081",
              "spring.rabbitmq.host": "rabbitmq"
              }'
          ports:
            - 8080:8080

        modelsservice:
          image: well5a/models-service:latest
          options: -h modelsservice --name modelsservice
          env:
            SPRING_DATA_MONGODB_USERNAME: tad
            SPRING_DATA_MONGODB_PASSWORD: tad
            SPRING_DATA_MONGODB_DATABASE: modelsdatabase
            SPRING_DATA_MONGODB_HOST: modelsdatabase
            SPRING_DATA_MONGODB_PORT: 27017
            TADM_OUTPUT_DIRECTORY: /usr/share/tadms
          volumes:
            - demaf:/usr/share
          ports:
            - 8081:8081

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      # validates, compile, test and packages it
      - name: Build Project
        run: sh ./mvnw package

      - name: Run
        run: sh. ./mvnw spring-boot:run



