# Runs Build without Docker
name: workflow-build

on:
  push:
    branches:
      - '*'

env:
  IMAGE_NAME: terraform-mps-plugin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

# validates, compile, test and packages it
      - name: Build Project
        run: sh ./mvnw package

      - name: Run
        run: sh. ./mvnw spring-boot:run



